spring.application.name=gt
server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

storage.s3.region=${AWS_REGION:us-east-1}
storage.s3.bucket=${AWS_BUCKET:change-me}
storage.s3.access-key=${AWS_ACCESS_KEY:change-me}
storage.s3.secret-key=${AWS_SECRET_KEY:change-me}
storage.s3.public-base-url=${AWS_PUBLIC_BASE_URL:https://change-me.s3.amazonaws.com}
