spring.application.name=gt
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5436/unimarket
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

storage.s3.region=us-east-1
storage.s3.bucket=change-me
storage.s3.access-key=change-me
storage.s3.secret-key=change-me
storage.s3.public-base-url=https://change-me.s3.amazonaws.com
